In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [ ]:
# Calculated the total 0 containing columns
invalid_columns = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
print(df[invalid_columns].eq(0).sum())

Glucose          0
BloodPressure    0
SkinThickness    0
Insulin          0
BMI              0
dtype: int64

In [ ]:
# Converting 0 values with NAN
df[invalid_columns] = df [invalid_columns].replace(0,np.nan)
print(df[invalid_columns].isnull().sum())

Glucose          0
BloodPressure    0
SkinThickness    0
Insulin          0
BMI              0
dtype: int64

In [ ]:
#Separating the features:
X= df.drop('Outcome',axis=1)
y = df['Outcome']

In [ ]:
X_train, X_test , y_train , y_test = train_test_split(
    X,y,
    test_size = 0.20,
    random_state = 42,
    stratify = y
)

In [ ]:
# Median imputation
for col in invalid_columns:
  median_value =X_train[col].median()

  X_train[col]=X_train[col].fillna(median_value)
  X_test[col]=X_test[col].fillna(median_value)

In [ ]:
X_train.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

In [ ]:
X_test.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

In [ ]:
# Feature scaling so that the large numerical values do not dominate other

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Model Training : Logistic Regression
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(X_train_scaled,y_train)
y_pred_lr = logistic_model.predict(X_test_scaled)
y_prob_lr = logistic_model.predict_proba(X_test_scaled)[:,1]

In [ ]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score

accuracy = accuracy_score(y_test,y_pred_lr)
precision = precision_score(y_test,y_pred_lr)
recall = recall_score(y_test,y_pred_lr)
f1=f1_score(y_test,y_pred_lr)
roc_auc = roc_auc_score(y_test,y_prob_lr)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-Score :", f1)
print("ROC-AUC  :", roc_auc)

Accuracy : 0.7077922077922078
Precision: 0.5882352941176471
Recall   : 0.5555555555555556
F1-Score : 0.5714285714285714
ROC-AUC  : 0.8262962962962963