In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.shape

(768, 9)

In [ ]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
#Select appropriate variables
glucose = df["Glucose"]
bmi = df["BMI"]
outcome = df["Outcome"]
print("\n Selected variables are:")
df[['Glucose','BMI','Outcome']].head()

 Selected variables are:

   Glucose   BMI  Outcome
0      148  33.6        1
1       85  26.6        0
2      183  23.3        1
3       89  28.1        0
4      137  43.1        1

In [ ]:
# Divide patients into diabetic and non-diabetic groups

diabetic_group = df[df["Outcome"]==1]
non_diabetic_group = df[df["Outcome"]==0]
print("\n Number of diabetic patients:",len(diabetic_group))
print("Number of non-diabetic patients:",len(non_diabetic_group))

 Number of diabetic patients: 268
Number of non-diabetic patients: 500

In [ ]:
# Display the groups
print("\nDiabetic Group:")
print(diabetic_group[["Glucose", "BMI", "Outcome"]].head())
print("\nNon-Diabetic Group:")
print(non_diabetic_group[["Glucose", "BMI", "Outcome"]].head())

Diabetic Group:
   Glucose   BMI  Outcome
0      148  33.6        1
2      183  23.3        1
4      137  43.1        1
6       78  31.0        1
8      197  30.5        1

Non-Diabetic Group:
    Glucose   BMI  Outcome
1        85  26.6        0
3        89  28.1        0
5       116  25.6        0
7       115  35.3        0
10      110  37.6        0

In [ ]:
# Point Estimation
# Sample mean of Glucose
sample_mean_glucose = glucose.mean()

print("\n--- Point Estimation ---")
print("Sample Mean of Glucose:",
      sample_mean_glucose)

--- Point Estimation ---
Sample Mean of Glucose: 120.89453125

In [ ]:
# Sample Proportion of Diabetic Patients
diabetic_count = (df["Outcome"] == 1).sum()
total_patients = len(df)

sample_proportion = diabetic_count / total_patients

print("Number of diabetic patients:",
      diabetic_count)

print("Total number of patients:",
      total_patients)

print("Sample Proportion of Diabetic Patients:",
      sample_proportion)

print("Percentage of Diabetic Patients:",
      sample_proportion * 100)

Number of diabetic patients: 268
Total number of patients: 768
Sample Proportion of Diabetic Patients: 0.3489583333333333
Percentage of Diabetic Patients: 34.89583333333333

In [ ]:
# Confidence interval for mean glucose
n = len(glucose)
mean_glucose = glucose.mean()
std_glucose = glucose.std()

confidence_level = 0.95
alpha = 1 - confidence_level

# Critical t-value
t_critical = stats.t.ppf(
    1 - alpha / 2,
    df=n - 1
)

# Standard error
standard_error = std_glucose / np.sqrt(n)

# Margin of error
margin_of_error = t_critical * standard_error

# Confidence interval
lower_limit = mean_glucose - margin_of_error
upper_limit = mean_glucose + margin_of_error

print("\n--- 95% Confidence Interval ---")
print("Sample Mean:", mean_glucose)
print("Standard Error:", standard_error)
print("Margin of Error:", margin_of_error)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)

print(
    f"\n95% Confidence Interval for population mean glucose: "
    f"({lower_limit:.2f}, {upper_limit:.2f})"
)

--- 95% Confidence Interval ---
Sample Mean: 120.89453125
Standard Error: 1.153712482603689
Margin of Error: 2.264808799054477
Lower Limit: 118.62972245094552
Upper Limit: 123.15934004905448

95% Confidence Interval for population mean glucose: (118.63, 123.16)

In [ ]:
# One sample t-test
# Research Question:
# Is the mean glucose level significantly different from 120?

# H0: Population mean glucose = 120
# H1: Population mean glucose != 120

reference_value = 120

t_statistic, p_value = stats.ttest_1samp(
    glucose,
    reference_value
)

print("\n--- One-Sample t-Test ---")
print("Reference Mean:", reference_value)
print("t-statistic:", t_statistic)
print("p-value:", p_value)

alpha = 0.05

if p_value < alpha:
    print("Decision: Reject H0")
    print("Conclusion: The mean glucose level is significantly different from 120.")
else:
    print("Decision: Fail to Reject H0")
    print("Conclusion: There is insufficient evidence that the mean glucose level differs from 120.")

--- One-Sample t-Test ---
Reference Mean: 120
t-statistic: 0.7753502397592414
p-value: 0.4383717099127056
Decision: Fail to Reject H0
Conclusion: There is insufficient evidence that the mean glucose level differs from 120.

In [ ]:
# Two sample t-test
diabetic_bmi = diabetic_group["BMI"]
non_diabetic_bmi = non_diabetic_group["BMI"]

# H0: Mean BMI of both groups is equal
# H1: Mean BMI of both groups is different

t_statistic, p_value = stats.ttest_ind(
    diabetic_bmi,
    non_diabetic_bmi,
    equal_var=False
)

print("\n--- Two-Sample t-Test ---")

print("Mean BMI of Diabetic Patients:",
      diabetic_bmi.mean())

print("Mean BMI of Non-Diabetic Patients:",
      non_diabetic_bmi.mean())

print("t-statistic:", t_statistic)
print("p-value:", p_value)

if p_value < alpha:
    print("Decision: Reject H0")
    print("Conclusion: There is a significant difference in mean BMI between diabetic and non-diabetic patients.")
else:
    print("Decision: Fail to Reject H0")
    print("Conclusion: There is insufficient evidence of a difference in mean BMI between the two groups.")

--- Two-Sample t-Test ---
Mean BMI of Diabetic Patients: 35.14253731343284
Mean BMI of Non-Diabetic Patients: 30.3042
t-statistic: 8.619316881357946
p-value: 6.566237624708332e-17
Decision: Reject H0
Conclusion: There is a significant difference in mean BMI between diabetic and non-diabetic patients.

In [ ]:
#Compare
alpha = 0.05

if p_value < alpha:
    print("Reject H0")
else:
    print("Fail to Reject H0")

Reject H0

In [ ]:
#Create BMI Categories
df["BMI_Category"] = np.where(
    df["BMI"] < 25,
    "Normal",
    "High"
)

df[["BMI", "BMI_Category", "Outcome"]].head()

    BMI BMI_Category  Outcome
0  33.6         High        1
1  26.6         High        0
2  23.3       Normal        1
3  28.1         High        0
4  43.1         High        1

In [ ]:
#Create table
table = pd.crosstab(
    df["BMI_Category"],
    df["Outcome"]
)

print(table)

Outcome         0    1
BMI_Category
High          392  259
Normal        108    9

In [ ]:
#Chi-Square Test
from scipy.stats import chi2_contingency

chi2, p_value, dof, expected = chi2_contingency(table)

print("Chi-Square Test")
print("Chi-Square Statistic:", chi2)
print("P-value:", p_value)
print("Degrees of Freedom:", dof)

Chi-Square Test
Chi-Square Statistic: 43.55929251297571
P-value: 4.1130645394492175e-11
Degrees of Freedom: 1

In [ ]:
#Compare
alpha = 0.05

if p_value < alpha:
    print("Reject H0")
else:
    print("Fail to Reject H0")

Reject H0